---
abstract: 'pack novel/bbs content to txt / html / jekyll / wordpress, etc'
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Novel-Robot-Packer
requires:
  Encode::Locale: '0'
  HTML::FormatText: '0'
  HTML::TreeBuilder: '0'
  XMLRPC::Lite: '0'
version: '0.16'
