=pod

=encoding utf8

=head1 NAME

L<Novel::Robot::Packer> 小说打包引擎

=head2 支持输出类型

    txt  : txt形式的小说

    html : 网页形式的小说

    wordpress : 将小说发布到WordPress空间

=head1 FUNCTION

=head2 new 初始化解析模块

   my $packer = Novel::Robot::Packer->new(type => 'html');

=head2 打包文件
   
   my $ret = $self->main($book_ref, 
       with_toc => 1, 
   );

=cut

