=pod

=encoding utf8

=head1 NAME

L<Novel::Robot::Packer> pack novel/bbs content to txt / html / jekyll / wordpress, etc

小说/贴子 打包引擎

=head2 支持输出类型

    txt  : txt文本格式

    html : html网页格式

    jekyll : md格式的jekyll网页文件

    wordpress : 将小说发布到WordPress空间

=head1 FUNCTION

=head2 new 初始化解析模块

   my $packer = Novel::Robot::Packer->new(type => 'html');

=head2 打包文件
   
   my $ret = $self->main($book_ref, 
       with_toc => 1, 
   );

=cut
